# **Array Creation**

1. Create a 1D NumPy array of integers from 10 to 19.
2. Create a 2D NumPy array of shape (3, 3) filled with zeros.
3. Create a 2D NumPy array of shape (4, 4) filled with ones.
4. Create a 1D NumPy array with values ranging from 0 to 50, with a step size of 5.
5. Create a 1D NumPy array with 10 equally spaced values between 1 and 20.




# **Array Operations**



1. Create two 1D NumPy arrays a and b of length 5 with arbitrary values. Perform element-wise addition, subtraction, multiplication, and division between these arrays.
2. Given two 2D arrays A and B, both of shape (2, 2), perform element-wise addition, subtraction, multiplication, and division

# **Indexing and Slicing**


1. Given a 1D array a of length 10, print the first element, last element, and elements from index 3 to 7.
2. Given a 2D array A of shape (4, 4), extract and print the element at row 2, column 3.
3. Modify the value at row 1, column 1 in a 3x3 array A to 99.

1. Create a 1D array of 20 integers and slice elements from index 5 to 15.
2. Given a 2D array A of shape (5, 5), extract and print the subarray consisting of the first three rows and all columns.

# **Reshaping**

1. Create a 1D array of 12 elements and reshape it into a 3x4 matrix.
2. Given a 2D array of shape (6, 4), reshape it to (3, 8).

# **Advanced Numpy Concepts**

In [1]:
import numpy as np

# Create a 2D array A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
#(a,b)=(row,column)
#axis(x,y)=(0,1): (0=column),(1=row)

# Calculate the sum of each column
column_sums = np.sum(A, axis=0)

# Calculate the sum of each row
row_sums = np.sum(A, axis=1)

# Print the results
print("Array A:")
print(A)
print("\nSum of each column:")
print(column_sums)
print("\nSum of each row:")
print(row_sums)


Array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of each column:
[12 15 18]

Sum of each row:
[ 6 15 24]


In [9]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Create a boolean array where condition is True
condition = a > 5
print(condition)


[False False False False False  True  True  True  True  True]


In [4]:
# Use boolean indexing to filter the array
filtered_a = a[condition]
print(filtered_a)


[ 6  7  8  9 10]


In [5]:
# Create a 1D array
b = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

# Condition for elements greater than 20 and less than 50
condition = (b > 20) & (b < 50)
print(condition)


[False False False  True  True  True  True  True False False]


In [6]:
# Filter elements
filtered_b = b[condition]
print(filtered_b)


[25 30 35 40 45]


In [11]:
indices = np.where(b > 5)
print(indices)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)


#Random Arrays

In [12]:
random_array = np.random.random(3)
print(random_array)


[0.69847981 0.78368495 0.89979012]


In [13]:
randint_array = np.random.randint(0, 10, 3)
print(randint_array)

[4 3 1]


In [ ]:
a = np.array([1, 2, 3, 4])
np.random.shuffle(a)
print(a)


In [19]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
choice = np.random.choice(a, 5)
print(choice)

[10 10 10  4  3]


#Sorting

In [20]:
a = np.array([3, 1, 2])
sorted_array = np.sort(a)
print(sorted_array)

[1 2 3]


In [21]:
a = np.array([1, 2, 3])
appended = np.append(a, [4, 5, 6])
print(appended)
# Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


#Stacking

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
hstacked = np.hstack((a, b))# horizontal
print(hstacked)
vstacked = np.vstack((a, b)) # vertical
print(vstacked)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
