# Numpy

1. NumPy - Numerical Python in Python Programming Language
2. It is a built-in library for all mathematical calculations
3. data type : Array []

In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr3= np.array([1,2,3,4,5])


In [ ]:
import numpy as np
# array = is a collection of Homogeneous data []
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print(type(arr1))


1D Array: [1 2 3 4 5]
<class 'numpy.ndarray'>


[1 2 3]
[4 5 6]
[7 8 9]

In [ ]:
# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print(type(arr2))


2D Array:
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
print("Shape of arr2:", arr2.shape)
print("Number of dimensions of arr2:", arr2.ndim)
print("Data type of elements in arr1:", arr1.dtype)


Shape of arr2: (2, 3)
Number of dimensions of arr2: 2
Data type of elements in arr1: int64


# **Different Ways of Initializing Numpy Arrays**

In [ ]:
# Array of zeros
zeros_array = np.zeros((8, 7))
print("Array of zeros:\n", zeros_array)

# (a,b) a=rows, b=col

Array of zeros:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Array of ones
ones_array = np.ones((7, 12))
print("Array of ones:\n", ones_array)
print(ones_array.dtype)

Array of ones:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
float64


In [ ]:

# Array with a range of values
range_array = np.arange(10, 20)
print("Array with a range of values:", range_array)
reshaped_array = range_array.reshape(5, 2)
print(reshaped_array)


Array with a range of values: [10 11 12 13 14 15 16 17 18 19]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:

# Array with evenly spaced values
linspace_array = np.linspace(0, 1, 4)
print("Array with evenly spaced values:", linspace_array)
# 1,2,3.............99,100

Array with evenly spaced values: [0.         0.33333333 0.66666667 1.        ]


# **Operations with Numpy arrays**

In [ ]:
#In Python Lists
nums1 = [1 ,2 ,3 ,4 ,5]
nums2 = [6, 7, 8, 9, 10]

print(nums1 + nums2)
print(nums1*2)
print(nums1 - nums2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
#In Numpy Array
n1 = np.array([10 ,12 ,35 ,42 ,50])
n2 = np.array([6, 7, 8, 9, 10])

print(n1 * 2)
print(n1 + n2)
print(n1 - n2)

[ 20  24  70  84 100]
[16 19 43 51 60]
[ 4  5 27 33 40]


In [ ]:
# Element-wise addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Element-wise addition:", a + b)

# Element-wise multiplication
print("Element-wise multiplication:", a * b)

# Dot product
print("Dot product:", np.dot(a, b))
# 1*4 = 4
# 2*5 = 10
# 3*6 = 18
# 32

Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Dot product: 32


# **Indexing and Slicing in Numpy arrays**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)

# Indexing
print("Element at (1, 2):", arr[1, 2])



Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6


In [ ]:
# Slicing
print("First two rows:\n", arr[:2])
print("Last column:\n", arr[:, -1])


First two rows:
 [[1 2 3]
 [4 5 6]]
Last column:
 [3 6 9]


In [ ]:
# Reshape array
reshaped_array = arr.reshape(1, 9)
print("Reshaped array:\n", reshaped_array)


Reshaped array:
 [[1 2 3 4 5 6 7 8 9]]


In [ ]:

# Flatten array
flattened_array = arr.flatten()
print("Flattened array:", flattened_array)


Flattened array: [1 2 3 4 5 6 7 8 9]


In [ ]:
print("Array:", arr)

# Sum
print("Sum of all elements:", np.sum(arr))

# Mean
print("Mean of all elements:", np.mean(arr))

# Standard deviation
print("Standard deviation:", np.std(arr))

# Maximum and minimum
print("Maximum element:", np.max(arr))
print("Minimum element:", np.min(arr))


Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Mean of all elements: 5.0
Standard deviation: 2.581988897471611
Maximum element: 9
Minimum element: 1


HomeWork

1. Create a 1D NumPy array of integers from 10 to 19.
2. Create a 2D NumPy array of shape (3, 3) filled with zeros.
3. Create a 2D NumPy array of shape (4, 4) filled with ones.
4. Create a 1D NumPy array with values ranging from 0 to 50, with a step size of 5.
5. Create a 1D NumPy array with 10 equally spaced values between 1 and 20. Random Arrays


